In [ ]:
# pandas : panel data or python data analysis

In [10]:
# Series : column in table , 1D array holding data of any type

import pandas as pd

a = [1,7,2]
myvar = pd.Series(a)
print(myvar)
# 0    1
# 1    7
# 2    2
# dtype: int64
print(myvar[2]) #2
# print(myvar[7]) KeyError: 7

myvar2 = pd.Series(a,index=['x','y','z'])
print(myvar2)
# x    1
# y    7
# z    2
# dtype: int64
print(myvar2['y']) #7
# print(myvar2['a']) KeyError: 'a'

b = [1.4,5,6,7]
var = pd.Series(b)
print(var)
# 0    1.4
# 1    5.0
# 2    6.0
# 3    7.0
# dtype: float64


c = [1.4,"5",6,7]
var1 = pd.Series(c)
print(var1)
# 0    1.4
# 1      5
# 2      6
# 3      7
# dtype: object

0    1
1    7
2    2
dtype: int64
2
x    1
y    7
z    2
dtype: int64
7
0    1.4
1    5.0
2    6.0
3    7.0
dtype: float64
0    1.4
1      5
2      6
3      7
dtype: object

In [2]:
import pandas as pd
student_name=["Ram","Shyam","Radha","Sita","Geeta"]
marks=[50,60,70,80,90]
varR = pd.Series(marks,index=student_name,name="Results")
print(varR)
# Ram      50
# Shyam    60
# Radha    70
# Sita     80
# Geeta    90
# Name: Results, dtype: int64

Ram      50
Shyam    60
Radha    70
Sita     80
Geeta    90
Name: Results, dtype: int64

In [5]:
import pandas as pd
calories = {'day1':400,'day2':350,'day3':430}
varC = pd.Series(calories)
print(varC)
# day1    400
# day2    350
# day3    430
# dtype: int64
varC = pd.Series(calories,index=['day1','day2'])
print(varC)
# day1    400
# day2    350
# dtype: int64
varC = pd.Series(calories,index=['d1','d2'])
print(varC)
# d1   NaN
# d2   NaN
# dtype: float64

day1    400
day2    350
day3    430
dtype: int64
day1    400
day2    350
dtype: int64

In [17]:
import pandas as pd
marks = {'Ram':80,'Shyam':70,'Seeta':78,'Geeta':90}
res = pd.Series(marks)

print(res)
# Ram      80
# Shyam    70
# Seeta    78
# Geeta    90
# dtype: int64

print(res.size) # number of entries --> Here : 4

print(res.dtype) # int64

print(res.name) # None

print(res.index) # Index(['Ram', 'Shyam', 'Seeta', 'Geeta'], dtype='object')

print(res.values) # [80 70 78 90] --> ARRAY (no commas)

print(res.is_unique) # True --> True or False according to the data if unique values : True

Ram      80
Shyam    70
Seeta    78
Geeta    90
dtype: int64
4
int64
None
Index(['Ram', 'Shyam', 'Seeta', 'Geeta'], dtype='object')
[80 70 78 90]
True

In [18]:
# CSV : Comma-Separated Values

In [33]:
import pandas as pd
subs = pd.read_csv("subs.csv") # DataFrame

print(subs)
#      Subscribers gained
# 0                    48
# 1                    57
# 2                    40
# 3                    43
# 4                    44
# ..                  ...
# 360                 231
# 361                 226
# 362                 155
# 363                 144
# 364                 172

# [365 rows x 1 columns]

print(type(subs))
# <class 'pandas.core.frame.DataFrame'>

print(subs.info())
# memory usage: 3.0 KB
# None

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Subscribers gained  365 non-null    int64
dtypes: int64(1)
memory usage: 3.0 KB
None

In [41]:
import pandas as pd
subs = pd.read_csv("subs.csv",squeeze=True) # Sqeeze works on Single column ONLY --> converts to SERIES

print(subs)
# 0       48
# 1       57
# 2       40
# 3       43
# 4       44
#       ... 
# 360    231
# 361    226
# 362    155
# 363    144
# 364    172
# Name: Subscribers gained, Length: 365, dtype: int64

print(type(subs)) #<class 'pandas.core.series.Series'>

subs.describe()
# count    365.000000
# mean     135.643836
# std       62.675023
# min       33.000000
# 25%       88.000000
# 50%      123.000000
# 75%      177.000000
# max      396.000000
# Name: Subscribers gained, dtype: float64

# 25%, 50% and 75% tells the values at 25%, 50% and 75% th index after arranging it in ascending order --> used in IQR
# IQR : interquartile range

print(subs.min()) # 33
print(subs.max()) # 396
print(subs.median()) # 123.0
print(subs.mean()) # 135.64383561643837
print(subs.sum()) # 49510

print(subs[subs>200])
# 165    225
# 166    249
# 167    265
# 168    306
# 169    261
# 170    222
# 225    224
# 226    254
print(subs[subs>200].size) # 59
print(subs[subs>200].count()) # 59

<class 'pandas.core.series.Series'>
33
396
123.0
135.64383561643837
49510
59
59

In [57]:
import pandas as pd
subs = pd.read_csv("subs.csv",squeeze=True)
s=subs[subs>100]
print(s[s<200].size) #181
print(subs[subs<200].size - subs[subs<100].size) #184

181
184

In [58]:
import pandas as pd
movies = pd.read_csv("bollywood.csv")

movies.info()
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 1500 entries, 0 to 1499
# Data columns (total 2 columns):
#  #   Column  Non-Null Count  Dtype 
# ---  ------  --------------  ----- 
#  0   movie   1500 non-null   object
#  1   lead    1500 non-null   object
# dtypes: object(2)
# memory usage: 23.6+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   movie   1500 non-null   object
 1   lead    1500 non-null   object
dtypes: object(2)
memory usage: 23.6+ KB

In [61]:
import pandas as pd
movies = pd.read_csv("bollywood.csv",index_col="movie",squeeze=True) # as there are 2 Columns we can convert it into Series
# if the columns are >2 it CAN'T be converted into SERIES
print(movies) 
# movie
# Uri: The Surgical Strike                   Vicky Kaushal
# Battalion 609                                Vicky Ahuja
# The Accidental Prime Minister (film)         Anupam Kher
# Why Cheat India                            Emraan Hashmi
# Evening Shadows                         Mona Ambegaonkar
#                                               ...       
# Hum Tumhare Hain Sanam                    Shah Rukh Khan
# Aankhen (2002 film)                     Amitabh Bachchan
# Saathiya (film)                             Vivek Oberoi
# Company (film)                                Ajay Devgn
# Awara Paagal Deewana                        Akshay Kumar
# Name: lead, Length: 1500, dtype: object
print(type(movies)) # <class 'pandas.core.series.Series'>

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object
<class 'pandas.core.series.Series'>

In [3]:
import pandas as pd
movies = pd.read_csv("bollywood.csv")

print(movies.head()) # first 5 records
#                                   movie              lead
# 0              Uri: The Surgical Strike     Vicky Kaushal
# 1                         Battalion 609       Vicky Ahuja
# 2  The Accidental Prime Minister (film)       Anupam Kher
# 3                       Why Cheat India     Emraan Hashmi
# 4                       Evening Shadows  Mona Ambegaonkar

print(movies.tail())
#                        movie              lead
# 1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
# 1496     Aankhen (2002 film)  Amitabh Bachchan
# 1497         Saathiya (film)      Vivek Oberoi
# 1498          Company (film)        Ajay Devgn
# 1499    Awara Paagal Deewana      Akshay Kumar

print(movies.tail(3))
#                      movie          lead
# 1497       Saathiya (film)  Vivek Oberoi
# 1498        Company (film)    Ajay Devgn
# 1499  Awara Paagal Deewana  Akshay Kumar

print(movies[:5]) # Same as HEAD
print(movies[-5:]) # Same as TAIL

print(movies[100:200])
#                              movie               lead
# 100            October (2018 film)       Varun Dhawan
# 101                 Mercury (film)        Prabhu Deva
# 102  Beyond the Clouds (2017 film)     Ishaan Khattar
# 103                  Nanu Ki Jaanu         Abhay Deol
# 104                       Daas Dev  Yogesh Raj Mishra
# ..                             ...                ...
# 195         Dobaara: See Your Evil       Adil Hussain
# 196                       Flat 211         Jayesh Raj
# 197                      Dear Maya    Manisha Koirala
# 198                  Raabta (film)   Deepika Padukone
# 199                Behen Hogi Teri      Rajkummar Rao

# [100 rows x 2 columns]

print(movies[::-1]) # whole dataframe reversed
print(movies[::2]) # alternate data entries

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar
                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar
                     movie          lead
1497       Saathiya (film)  Vivek Oberoi
1498        Company (film)    Ajay Devgn
1499  Awara Paagal Deewana  Akshay Kumar
                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar
                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar
                             movie               lead
100            October (2018 film)       Varun Dhawan
101                 Mercury (film)        Prabhu Deva
102  Beyond the Clouds (2017 film)     Ishaan Khattar
103                  Nanu Ki Jaanu         Abhay Deol
104                       Daas Dev  Yogesh Raj Mishra
..                             ...                ...
195         Dobaara: See Your Evil       Adil Hussain
196                       Flat 211         Jayesh Raj
197                      Dear Maya    Manisha Koirala
198                  Raabta (film)   Deepika Padukone
199                Behen Hogi Teri      Rajkummar Rao

[100 rows x 2 columns]
                                     movie              lead
1499                  Awara Paagal Deewana      Akshay Kumar
1498                        Company (film)        Ajay Devgn
1497                       Saathiya (film)      Vivek Oberoi
1496                   Aankhen (2002 film)  Amitabh Bachchan
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
...                                    ...               ...
4                          Evening Shadows  Mona Ambegaonkar
3                          Why Cheat India     Emraan Hashmi
2     The Accidental Prime Minister (film)       Anupam Kher
1                            Battalion 609       Vicky Ahuja
0                 Uri: The Surgical Strike     Vicky Kaushal

[1500 rows x 2 columns]
                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
2     The Accidental Prime Minister (film)       Anupam Kher
4                          Evening Shadows  Mona Ambegaonkar
6                            Fraud Saiyaan      Arshad Warsi
8         Manikarnika: The Queen of Jhansi    Kangana Ranaut
...                                    ...               ...
1490                      Raaz (2002 film)        Dino Morea
1492            Waisa Bhi Hota Hai Part II      Arshad Warsi
1494                                Kaante  Amitabh Bachchan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1498                        Company (film)        Ajay Devgn

[750 rows x 2 columns]

In [16]:
import pandas as pd
movie = pd.read_csv("bollywood.csv",index_col="movie",squeeze=True)

print(movie[[1,4,5,8]]) # Specific indexes
# movie
# Battalion 609                                Vicky Ahuja
# Evening Shadows                         Mona Ambegaonkar
# Soni (film)                         Geetika Vidya Ohlyan
# Manikarnika: The Queen of Jhansi          Kangana Ranaut
# Name: lead, dtype: object

print(movie["Total Dhamaal"]) # Ajay Devgn

print(movie.value_counts()) 
# Akshay Kumar          48
# Amitabh Bachchan      45
# Ajay Devgn            38
# Salman Khan           31
# Sanjay Dutt           26
#                       ..
# Kanika Batra           1
# Chandan Roy Sanyal     1
# Jahangir Khan          1
# Arsh Bajwa             1
# Kunaal Roy Kapur       1
# Name: lead, Length: 566, dtype: int64
print()
count = movie.value_counts()
print(count[count>20])

# Akshay Kumar        48
# Amitabh Bachchan    45
# Ajay Devgn          38
# Salman Khan         31
# Sanjay Dutt         26
# Shah Rukh Khan      22
# Emraan Hashmi       21
# Name: lead, dtype: int64

movie
Battalion 609                                Vicky Ahuja
Evening Shadows                         Mona Ambegaonkar
Soni (film)                         Geetika Vidya Ohlyan
Manikarnika: The Queen of Jhansi          Kangana Ranaut
Name: lead, dtype: object
Ajay Devgn
Akshay Kumar          48
Amitabh Bachchan      45
Ajay Devgn            38
Salman Khan           31
Sanjay Dutt           26
                      ..
Kanika Batra           1
Chandan Roy Sanyal     1
Jahangir Khan          1
Arsh Bajwa             1
Kunaal Roy Kapur       1
Name: lead, Length: 566, dtype: int64

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64